name: my ci
on:
 push:
 workflow_dispatch:
jobs:
 test:
  runs-on: ubuntu-latest
  steps: 
   - name: Test
     run: exit 1
   - name: Build
     run: echo "build this file"
   - name: Report Failure
     if: failure()
     run: echo "Test failed"


 build:
  needs: test
  runs-on: ubuntu-latest
  steps: 
   - name: print build
     run: echo "this is build"
