name: ci-job
on:
 push:
jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    
   - name: print-ci
     run: echo "hello this is test"
 build:
  runs-on: ubuntu-latest
  steps:

   - name: build-ci
     run: echo "this is build "


