name: my first ci 
on:
 push:
jobs:
 dani: 
  runs-on: ubuntu-latest
  steps:
   - name: say dani
     run: echo "Hello CI/CD"
   - name: show current directory
     run: pwd
   - name: checkout
     uses: actions/checkout@v4
   - name: List files
     run: ls

